edition = "2018"
imports_granularity = "Module"
normalize_doc_attributes = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
wrap_comments = true
